name: random_face_generator
description: This app Generates Random Faces which do not actually exist.

publish_to: 'none' 

version: 2.1.0+4

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  download: ^0.0.1+1
  path_provider: ^2.0.9
  flutter_native_splash: ^2.1.6
  animated_theme_switcher: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter_native_splash:
  color: "#E0E5EC"
  image: "assets/app_icon.png"
  color_dark: "#292D32"
  image_dark: "assets/app_icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
